-- MySQL Script generated by MySQL Workbench
-- Sun Nov 18 15:17:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema std_management
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `password` VARCHAR(32) NOT NULL,
  `school` VARCHAR(45) NULL,
  `major` VARCHAR(45) NULL,
  `student_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `grade` INT NULL,
  `birth` DATE NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `admin_id` VARCHAR(45) NOT NULL,
  `admin_password` VARCHAR(45) NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subject_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subject_plan` (
  `plan_info` VARCHAR(100) NOT NULL,
  `plan_prelearn` VARCHAR(45) NULL,
  `plan_howteach` VARCHAR(45) NULL,
  `plan_howscore` VARCHAR(45) NULL,
  `plan_object` VARCHAR(45) NULL,
  `plan_operate` VARCHAR(45) NULL,
  `plan_activate` VARCHAR(45) NULL,
  `plan_rule` VARCHAR(45) NULL,
  `plan_refbook` VARCHAR(45) NULL,
  `plan_weekplan` VARCHAR(45) NULL,
  `plan_ref` VARCHAR(45) NULL,
  `plan_handi` VARCHAR(45) NULL,
  `plan_id` INT NOT NULL,
  PRIMARY KEY (`plan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subject` (
  `subject_semester` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `subject_name` VARCHAR(45) NOT NULL,
  `subject_score` VARCHAR(45) NOT NULL,
  `subject_major` VARCHAR(45) NOT NULL,
  `subject_prof` VARCHAR(45) NOT NULL,
  `subject_time` VARCHAR(45) NOT NULL,
  `subject_plan` INT NULL,
  PRIMARY KEY (`subject_id`),
  INDEX `subject_plan_idx` (`subject_plan` ASC),
  CONSTRAINT `subject_plan`
    FOREIGN KEY (`subject_plan`)
    REFERENCES `mydb`.`subject_plan` (`plan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student_subject` (
  `student_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `student_grade` VARCHAR(45) NULL,
  PRIMARY KEY (`student_id`, `subject_id`),
  INDEX `subject_id_idx` (`subject_id` ASC),
  CONSTRAINT `subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `mydb`.`subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
